export const COMPONENT_LIST = [
  { name: 'AnimatedSection', colors: ['#FECACA', '#F97316'], emoji: '🧱' },
  { name: 'Avatar', colors: ['#FDE68A', '#22C55E'], emoji: '🪪' },
  { name: 'Button', colors: ['#6366F1', '#F59E0B'], emoji: '🔘' },
  { name: 'FlashList', colors: ['#22D3EE', '#3B82F6'], emoji: '⚡️' },
  { name: 'Form', colors: ['#10B981', '#8B5CF6'], emoji: '📝' },
  { name: 'Icon', colors: ['#8B5CF6', '#D946EF'], emoji: '🔣' },
  { name: 'LineGraph', colors: ['#38BDF8', '#22D3EE'], emoji: '📈' },
  { name: 'PieChart', colors: ['#6366F1', '#22D3EE'], emoji: '🥧' },
  { name: 'Pressable', colors: ['#34D399', '#F97316'], emoji: '👆' },
  { name: 'Sheet', colors: ['#FDBA74', '#FBBF24'], emoji: '🪟' },
  { name: 'Skeleton', colors: ['#CBD5F5', '#9CA3AF'], emoji: '🦴' },
  { name: 'Image', colors: ['#60A5FA', '#F87171'], emoji: '🖼️' },
  { name: 'ListItem', colors: ['#818CF8', '#F472B6'], emoji: '🧾' },
  { name: 'Tabs', colors: ['#F43F5E', '#FB7185'], emoji: '🗂️' },
  { name: 'Typography', colors: ['#38BDF8', '#F472B6'], emoji: '✍️' },
  { name: 'View', colors: ['#F43F5E', '#22D3EE'], emoji: '📐' },
  { name: 'XStack', colors: ['#F59E0B', '#38BDF8'], emoji: '➡️' },
  { name: 'YStack', colors: ['#84CC16', '#22C55E'], emoji: '🧱' },
] as const;
