name: Create Production Builds

jobs:
  ios_build:
    type: build
    params:
      platform: ios
      profile: production

  ios_submit:
    type: submit
    needs: [ios_build]
    params:
      build_id: ${{ needs.ios_build.outputs.build_id }}
      profile: production

  android_build_apk:
    type: build
    params:
      platform: android
      profile: production
